server:
  port: 8082
  servlet:
    context-path: /renren-generator


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/renren_security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: renren
#    password: 123456
    #oracle配置
#    driverClassName: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@192.168.10.10:1521:helowin
#    username: renren
#    password: 123456
    #SQLServer配置
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://192.168.10.10:1433;DatabaseName=renren_security
#    username: sa
#    password: 123456
    #PostgreSQL配置
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://192.168.10.10:5432/renren_security
#    username: postgres
#    password: 123456
#   瀚高数据库配置
    driverClassName: com.highgo.jdbc.Driver
    url: jdbc:highgo://localhost:5866/renren_security
    username: highgo
    password: hg123456
    validation-query: select version()
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/

mybatis:
  mapperLocations: classpath:mapper/**/*.xml
#  config-location: classpath:mybatis-config.xml

pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  helper-dialect: postgresql


#指定数据库，可选值有【mysql、oracle、sqlserver、postgresql】
renren:
  database: postgresql